#!/bin/bash
#
# Regards, the Alveare Solutions society.
#
declare -A PW_DEFAULT
declare -A PW_LIB
declare -A PW_SOURCE
declare -A PW_IMPORTS
declare -A PW_PAYLOAD
declare -A PW_CARGO

# [ NOTE ]: Absolute directory path the current file is in.
PW_DIRECTORY="$(
    cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd
)"
CONF_FILE_PATH="$PW_DIRECTORY/conf/wormhole.conf"

if [ ! -f "$CONF_FILE_PATH" ]; then
    echo "[ WARNING ]: Config file ($CONF_FILE_PATH) not found."
    return 1
else
    source "$CONF_FILE_PATH"
fi

for script in ${!PW_SOURCE[@]}; do
    source ${PW_SOURCE[$script]}
    if [ $? -ne 0 ]; then
        echo "[ NOK ]: Something went wrong."\
            "Could not load ($script) script."
    else
        echo "[ OK ]: Successfully loaded ($script) script."
    fi
done

for library in ${!PW_LIB[@]}; do
    source ${PW_LIB[$library]}
    if [ $? -ne 0 ]; then
        echo "[ NOK ]: Something went wrong."\
            "Could not load ($library) library."
    else
        echo "[ OK ]: Successfully loaded ($library) library."
    fi
done

# MISCELLANEOUS

function init_wormhole () {
    wormhole_project_setup
    display_wormhole_banner
    init_menu 'MainController'
}

init_wormhole
